### ISSUE TITLE
4.x builds are broken since recipe plugin has been added to installer

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-travis-support#48]
Since the recipe plugins were added to the 4 branch of installer, Travis builds do not work with this module any more.

```
PHP Fatal error:  Class 'Page' not found in /home/travis/builds/ss/cms/code/Model/RedirectorPage.php on line 21
PHP Stack trace:
PHP   1. {main}() /home/travis/builds/ss/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /home/travis/builds/ss/vendor/phpunit/phpunit/phpunit:52
PHP   3. PHPUnit_TextUI_Command->run() /home/travis/builds/ss/vendor/phpunit/phpunit/src/TextUI/Command.php:116
PHP   4. PHPUnit_TextUI_TestRunner->doRun() /home/travis/builds/ss/vendor/phpunit/phpunit/src/TextUI/Command.php:186
PHP   5. PHPUnit_Framework_TestSuite->run() /home/travis/builds/ss/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:517
PHP   6. PHPUnit_Framework_TestSuite->run() /home/travis/builds/ss/vendor/phpunit/phpunit/src/Framework/TestSuite.php:722

...
```

Examples:

* https://travis-ci.org/silverstripe/silverstripe-segment-field/jobs/267435503
* https://travis-ci.org/silverstripe/silverstripe-activedirectory/jobs/266648790

https://github.com/silverstripe/silverstripe-installer/blob/4/composer.json

We need to update ComposerGenerator to include these recipe plugins.

**Comment by tractorcow** [comment]
We should not be using travis-support module for 4.x anymore. Fix is to migrate off that to using `.travis.yml` exclusively.

**Comment by robbieaverill** [comment]
I mentioned this to @sminnee - perhaps we need to communicate this change more clearly to the community?

**Comment by tractorcow** [comment]
At the moment the primary issue seems just making sure our own modules are up to date.

**Comment by robbieaverill** [comment]
Ok, closing. Do you think we should throw an exception in this module when core release is master or 4?
