### ISSUE TITLE
Selenium Configuration isn't nice.

### ISSUE THREAD

**Issue by srizzling** [silverstripe/silverstripe-travis-support#8]
Currently, this module uses a hard coded url to download selenium. It might be nice to add a yml file, so it makes it easier to upgrade to different version :)

If this okay, I might make a PR

**Comment by srizzling** [comment]
I'm gonna close this issue since, I have no idea what it means to me anymore. But 👋 @tractorcow

**Comment by tractorcow** [comment]
Well we don't use selenium by default anymore anyway. We use chromedriver mostly. :)
